openapi: '3.0.3'
info:
  version: 1.0.0
  title: allOf with a discriminator with mapping
paths:
  /survey/{surveyId}:
    get:
      operationId: getSurvey
      parameters:
        - name: surveyId
          in: path
          description: Survey id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Survey'

components:
  schemas:
    QuestionTypeEnum:
      type: string
      enum:
        - q1
        - q2

    Question:
      type: object
      required: [type, title]
      discriminator:
        propertyName: type
        mapping:
          q1: '#/components/schemas/Question1'
          q2: '#/components/schemas/Question2'
      properties:
        type:
          $ref: '#/components/schemas/QuestionTypeEnum'
        title:
          type: string
          description: Question title
    Question1:
      allOf:
        - $ref: '#/components/schemas/Question'
        - $ref: '#/components/schemas/AbstractQuestion1'
        - type: object
          properties:
            notApplicableOption:
              type: string
    AbstractQuestion1:
      type: object
      required: [min, max]
      properties:
        min: 
          type: integer
        max: 
          type: integer
    Question2:
      allOf:
        - $ref: '#/components/schemas/Question'
        - type: object
          required: [freeTextType]
          properties:
            freeTextType:
              type: string
              enum: [short, long]

    Survey:
      type: object
      required: [questions]
      properties:
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'
