openapi: '3.0.3'
info:
  title: Test Binary
  version: '1.0'
paths:
  /test1:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: binary
  /test2:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: OK
  /test3:
    get:
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /test4:
    post:
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: OK

components:
  schemas:
    BinaryResult:
      type: object
      properties:
        value:
          type: string
          format: binary
          default: Test
