---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: Example
  description: allOfs with a parent property of a conflicting type or configuration
paths: {}
components:
  schemas:
    Parent:
      required:
        - name
      properties:
        name:
          type: string
    ChildTypes:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
          required:
            - name
          properties:
            name:
              type: integer
    ChildNullability:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
          required:
            - name
          properties:
            name:
              type: string
              nullable: true
    ChildRequired:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
          properties:
            name:
              type: string
    ControlChild:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
          required:
            - name
          properties:
            name:
              type: string
