openapi: '3.0.3'
info:
  title: Content with no schema
  version: '1.0'
paths:
  /test1:
    get:
      description: Missing a response schema
      parameters:
        - name: a
          in: query
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            text/plain: {}
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: string
        423:
          description: No response
  /test2:
    get:
      description: Missing parameter schemas
      parameters:
      - name: param1
        in: query
        description: Missing schema
        required: false
      responses:
        200:
          description: OK
          headers:
            ResponseHeader:
              description: A response header without a schema
  /test3:
    post:
      description: Missing request body schema
      requestBody:
        content:
          application/json: {}
      responses:
        200:
          description: OK
