openapi: '3.0.3'
info:
  title: Operations
  version: '1.0'
paths:
  /no-schemas:
    get:
      description: Request body and response are missing the schema
      requestBody:
        content:
          application/json: {}
      responses:
        200:
          description: OK
          content:
            application/json: {}
        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: string
        423:
          description: No response
